language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
script: nosetests --with-coverage --cover-package=fanpy
after_success:
  - coveralls
  - pip install pep8 pyflakes
  - pep8 fanpy/*.py
  - pyflakes fanpy/*.py
  - pep8 tests/*.py
  - pyflakes tests/*.py
