language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false
install:
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=fanpy
after_success:
  - coveralls
